language: rust
sudo: false
os:
  - linux
  - osx

rust:
  - nightly

before_script:
  - if [ ${TRAVIS_OS_NAME} == "osx" ] ; then
         export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)/include
      && export DEP_OPENSSL_INCLUDE=$(brew --prefix openssl)/include;
    fi


script:
  cargo build

cache: cargo

env:
  global:
    - BUILD_DIRECTORY=*
    - TRELLOBST_DIR=${HOME}/.TrelloBST
    - TRELLOBST_EXEC=${TRELLOBST_DIR}/TrelloBST-${TRAVIS_OS_NAME}
    - secure: LW4tB4mUtDaNBaeCns8SGM1hg73VqmFWp9NS3gq74WbX3gzLJkwo/BfV0WP6IEPuCQUmQprDxT04vfZ7ZodMQ8H2X1pnKONqjTYyqH5DxMzOn6aaJ/Q9qmrqzkP+FzpuRTblbTvfe07gxzkKtM/JDG1DiRti6CmpJjx9ZKuxY9HQHOssfJzHXmtA/2SGv49Ui2LitZsoP3f9ipAGZuDf7+vc8QLV03wqe5zcHcWqfvMLm+LfxRdUjsAUvCCBonHtzMy7q8qJkndGXYTHERGk1ZzQ1XvnJSJEPsR6QtqI2ZehCq7q/WpTsTmPwLS5zFZM07FcxQjLmR7W3f+cz7WF7gD3U29N0pQ9efFFvs95b4RSCIg7ZEMJWOyHEmVD+uiXtVPexc6z6aZx5iG1zeABwzqnNpt1Mo4PbrMzvbsr2ymLIaZQdTYagF0sWsroc/x9z3gKJd0a5y8LxrJrrYTSw1S12hTXcuQyCAgMmA7195XiBuagB1VSujNrmrRTkg06eMByAASDTeyn0NVfKGem/OfPx7L2WMiWyLdBor9B2RGrsqTv1QoViLGs1HrY44LpapdB4bhz95cGtl9pomnJHXo+pXY48Se8Czx7vDqSnrbe7Fw/k5hTJ0DjRabeOowxhT0qkXmSN9pu2PSOsY/RbkW4Hffgu5iIMDd+wTLL3TI=
    - secure: bvmWoGOS8v0V0Lfva2MotD9wi+hrra7PYZ5igC81EUN3Ocaee7bAQv5eD+L6m7ShvpX1CdNLLQoR/8FyDMaXUDM6ESAbR/dKDXIXYk70WS4mF++YxDpy6rnS5XwC7lxGMp9rPUFn0rD1RtmV5mxIFvrgfXCXxjO8Z/2Eut+CgrjK6EPtt4y31ZmO+ecT1Ai1fQ8kZP9C1Z7nFM192zdZX5d8wu/QoAPWB+YwzsQbjQknnm8/eevsbliA46X2wwdMQP5qKLWUwFZt4lZ+jJHVk1mGFPrV9zRBYkM4oCUcLUnlFdGVHNY5Zm7ENI20SDgCu6QUPnEbMExNWFXCfzJdFvtn7rX+gHdOJ4IQl2Wuy1uhemOKn5rLIhmiekFVHr8jM7PeJG/AFpgEGt0b7yq2/O+z1akuVhkyoN6QTCZeTTvdrZUJ1YTCa+aLgJ0EcCz99qZZn/CWOieu+Lrul7RhJgwCP25t6McPPVd1/fYgDSowfklPBEFAnpe4xDe4wh55aotXcaCecjirfERyw73lVRl4KxhW1LOfWqIMDENRsyPA2W1LPMImHFEJrXMuUrHzkf32vvclrU6r0D3y7Bba2SadvjbsbAozSqm23D04Ndq/KcL9261xevDIpojkWVs/fqr0bMp0hmQuxl4dOcKpLTLiBMepJbAgcatmxMah458=
    - secure: K+dOn3s51YloBuCDE1MT8QDzysL6a5Ftmj2DJWKs/17Gj+WT6OVF8xgCm1MqNCeQmEUiWFQR2yaYQyb2xAN+2Sa41QDPYVYJLGNHbsUFDAbYXPg9Xwy1QDPyZzzA4b+kflAVI+8Y286ouzGncNbhHM4lIPpvPEa88/v4UbFMek6sYKuaFVLpcvpbHsjoVxUvrNl5jKqxGoPQ+AwWygDsZsdZu3jtyJ+IWMmkaZ9/aCpKgKLPhOCostWY4Ip0ZfP91I0welpm5BVCWjS2yFLC7N89pnQRCUb/lv978Da2ljsc+Z+y6eTXg85u0qWKHYgTOlTavTgZEsH3Jlb9qgJ8U2Wd0xDLxGsjA9jXHzgOGQ4u3GNkhRcplK66PIlrAUK2IAPxh0IuX9JZi1E9iIPuaNCjuumIe6ES1/ppuZvYP2R4oigxSChliJvEIhdJeNEC/mpcmzjWm0Xke77u2BkVsrw51kl+ql45JJMg82XgwRwYc76nl6pKbSDWs1l/92vkgyhFa4JheAXrvrdd5Bn4k8L9QA3qE4M8ySNcEykmiS6H+zFDcTEHjWIrw61O4SWEL3Mj0Y0IgZ40spVTiEr9AjryS95yzM7sWoqdP7GpsBlgw3K21lBU0t2iGom8k1FQSceCA6nfyDyrPe3DMODnZmtArl3/fEjGHdBV2+zV/xM=
    - secure: RJ1Y4UwmNMn4EE9fgVt34XF5wPayeIxNpzvtuRmdEnMqXnE+hDoIAhkMa++cAazrWf1nxhxu/FvLH+9cDWDi1kBGa0Ih2X6fX/jxUZQcny2qUEIm9YYWhnemzTHUpVky/oASb91DYadfbTptD0Kxz2t3uXxHlkhJsMnha8tGmOD/VMf6EvLVdib3dyZc9uxenKMynpNp/mwvfPzzzRLnfqcERyg1L0YLPK7swb3ytSrBxRvtfuJSpgDFviCd+e5yVWz9DIwEP4xf/12FftAP/8oL5GA+61ykxMfZFOCCIR749B9R/aXZzxkA8rI8BsUQptu+826UcFkBlewBXUaqiCF9TSS/ciCnAS0h3aJhEsh3EOa2P7vkHRSUVufgLsaz7IWpg+yrP/z8Rhl01Baxh41jJStZlLWxbciYEuGPtIv5f6nL4LkkOAOu5gf+ClGMDOf7YR+8k71OoAhIq8xHTn1kiGGptDXz9ejVDrpvu+XTgDgAQVqrT4sEFIxHyntn7XNIunwo0PBL1JVKugKUjVgMSjOoK8Pqj/vAXVTXBcga72Z8m/DJsi1WBUMscYIOVVQTZenm3o1YOPyQ5TgsYwSgwPt46kGSLbS41doZS6Ay+f5SJ4BawX33buJ10tF9AdkhPdSzneo7340Z2QtdXIthP6zsskBQeF484Om2ehQ=

before_install:
  - wget -q https://github.com/Cyberunner23/TrelloBST/releases/download/v2.0.0-pre1/Travis-${TRAVIS_OS_NAME}-stable.tar.gz
  - mkdir ${TRELLOBST_DIR}
  - tar -xvf Travis-${TRAVIS_OS_NAME}-stable.tar.gz -C ${TRELLOBST_DIR}

after_success:
  - if [ ! -z ${TRAVIS_TAG} ] ; then
           cargo doc
        && mkdir -p ~/.ssh
        && openssl aes-256-cbc -K $encrypted_d9ac7fa35307_key -iv $encrypted_d9ac7fa35307_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
        && chmod 600 ~/.ssh/id_rsa
        && mv ./target/doc ${HOME}/doc
        && mv ./.git ${HOME}/.git
        && git config user.name "doc upload bot"
        && git config user.email "nobody@example.com"
        && git checkout gh-pages
        && rm -rf *
        && mv ${HOME}/doc ./
        && mv ${HOME}/.git ./.git
        && git add *
        && git commit -a -m "Doc upload."
        && git push -q origin gh-pages;
    fi
  - 'if [ ${TRAVIS_SECURE_ENV_VARS} = true ] ; then
           tar -zcf build.tar.gz ${BUILD_DIRECTORY}
        && export BUILD_LINK=$(curl --upload-file ./build.tar.gz https://transfer.sh/build.tar.gz)
        && export TRELLO_CARD_TITLE="[${TRAVIS_BRANCH}][Travis-CI][${TRAVIS_OS_NAME}][gcc]: #${TRAVIS_BUILD_NUMBER} PASSED"
        && export TRELLO_CARD_DESC="[Build]\: ${BUILD_LINK}"$''\n''"[Logs]\: https://travis-ci.org/${TRAVIS_REPO_SLUG}/jobs/${TRAVIS_JOB_ID}"
        && ${TRELLOBST_EXEC} push --pass --title "${TRELLO_CARD_TITLE}" --description "${TRELLO_CARD_DESC}";
    fi'

after_failure:
  - 'if [ ${TRAVIS_SECURE_ENV_VARS} = true ] ; then
           export TRELLO_CARD_TITLE="[${TRAVIS_BRANCH}][Travis-CI][${TRAVIS_OS_NAME}][gcc]: #${TRAVIS_BUILD_NUMBER} FAILED"
        && export TRELLO_CARD_DESC="[Logs]\: https://travis-ci.org/${TRAVIS_REPO_SLUG}/jobs/${TRAVIS_JOB_ID}"
        && ${TRELLOBST_EXEC} push --fail --title "${TRELLO_CARD_TITLE}" --description "${TRELLO_CARD_DESC}";
    fi'
