
build_script:
  - cmd: cargo build

cache:
  - '%UserProfile%\.cargo'

environment:
  OPENSSL_LIB_DIR: C:\OpenSSL\lib\VC
  OPENSSL_LIBS: ssleay32MD:libeay32MD
  OPENSSL_INCLUDE_DIR: C:\OpenSSL\include
  BUILD_DIRECTORY: .\target
  TRELLOBST_DIR: '%APPVEYOR_BUILD_FOLDER%\TrelloBST'
  TRELLOBST_EXEC: '%TRELLOBST_DIR%\TrelloBST.exe'
  TRELLO_API_TOKEN:
    secure: OyiLx3CAYMpm6S7ThydKAJnW5osW2TvI5Ex8EHa/Qet0Jx2DldxQiHeXCzq9npmDYHa6UsxOHuXJGLgGhIeN7Sx3Pwrci1Y83eZU8CHb0XM=
  TRELLO_API_LIST_ID:
    secure: wtQVUHP4/Tfc17pi0ALcDtyLBaGawKZU6gGUUFu8x24=
  TRELLO_API_BUILD_PASS_ID:
    secure: ER42T8YtQQDUbDssWsNzEE2peCA6gcTKavPyF+Bjcqc=
  TRELLO_API_BUILD_FAIL_ID:
    secure: Rlf5WTk1uy980xtAo4Ak4lbOG4wmrFBidVT5uQMwphY=

install:
  - ps: Start-FileDownload "https://slproweb.com/download/Win64OpenSSL-1_0_2j.exe"
  - Win64OpenSSL-1_0_2j.exe /SILENT /VERYSILENT /SP- /DIR="C:\OpenSSL"
  - ps: |
        .\appveyor_rust_install.ps1 nightly
        Invoke-WebRequest "https://github.com/Cyberunner23/TrelloBST/releases/download/v2.0.0-pre1/AppVeyor-win-stable.zip" -OutFile "./AppVeyor-win-stable.zip"
        New-Item -ItemType directory -Path "$($env:TRELLOBST_DIR)" > $null
        &'7z' e -y .\AppVeyor-win-stable.zip * > $null
        Move-Item "$($env:APPVEYOR_BUILD_FOLDER)\TrelloBST.exe" $($env:TRELLOBST_DIR) > $null

on_success:
  - ps: Remove-item alias:curl
  - ps: cd $($env:BUILD_DIRECTORY)
  - ps: 7z a -r build.zip .\ > $null
  - ps: $BUILD_LINK         = [string](curl --silent --upload-file .\build.zip https://transfer.sh/build.zip)
  - ps: '$TRELLO_CARD_TITLE = "[$($env:APPVEYOR_REPO_BRANCH)][AppVeyor][Windows][$($env:COMPILER)]: #$($env:APPVEYOR_BUILD_NUMBER) PASSED"'
  - ps: '$TRELLO_CARD_DESC  = "[Build]\: $($BUILD_LINK)`n[Logs]\:https://ci.appveyor.com/project/$($env:APPVEYOR_REPO_NAME)/build/$($env:APPVEYOR_BUILD_VERSION)/job/$($env:APPVEYOR_JOB_ID)"'
  - ps: '&"$($env:TRELLOBST_EXEC)" push --pass --title "$($TRELLO_CARD_TITLE)" --description "$($TRELLO_CARD_DESC)"'

on_failure:
  - ps: Remove-item alias:curl
  - ps: '$TRELLO_CARD_TITLE = "[$($env:APPVEYOR_REPO_BRANCH)][AppVeyor][Windows][$($env:COMPILER)]: #$($env:APPVEYOR_BUILD_NUMBER) PASSED"'
  - ps: $TRELLO_CARD_DESC   = "[Logs]\:https://ci.appveyor.com/project/$($env:APPVEYOR_REPO_NAME)/build/$($env:APPVEYOR_BUILD_VERSION)/job/$($env:APPVEYOR_JOB_ID)"
  - ps: '&"$($env:TRELLOBST_EXEC)" push --fail --title "$($TRELLO_CARD_TITLE)" --description "$($TRELLO_CARD_DESC)"'
